---
- name: Configure MongoDB
  hosts: mongodb
  become: yes
  tasks:
    - name: Install docker-compose
      apt: 
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Clone repo
      git:
        repo: https://github.com/aaronpaulcatabas/mern-gallery-sample-app.git
        dest: /opt/app

    - name: Start MongoDB
      command: docker-compose up -d
      args:
        chdir: /opt/app/ec2-mongodb